### ISSUE TITLE
Button inside the pop-up to quickly copy to the clipboard

### ISSUE THREAD

**Issue by Terkyz** [translate-tools/linguist#384] opened 2023-07-29 17:08 UTC
Maybe I'm missing something, I've already looked in other Issues and found nothing, but I think it would be great to have [a little Clipboard button](https://i.imgur.com/ujv42LN.png) that automatically copies what the user translated to his clipboard, just like any translation app.

**Comment by vitonsky** [comment] 2023-07-29 18:38
I will implement this feature in next release, thanks for your activity, your vote are counted.

It looks this issue are duplicate of #301. I close this issue, if you have other vision how it should be implemented, feel free to elaborate your thoughts in #301

**Closed** 2023-07-29 18:38 UTC
