### ISSUE TITLE
Make "Text Translation" display as a separate window.

### ISSUE THREAD

**Issue by XM-8JD2** [translate-tools/linguist#516] opened 2024-09-25 14:40 UTC
## What problem do you have?
When switching windows, I often need to click on Linguist to open the text translation window, instead of just keeping a specific independent page selected and clicking anywhere on the page to keep the cursor in the text input box and start typing immediately.

## Why you need this changes and how this changes will solve your problem?
I frequently need to translate words and sentences, which means I have to click from other windows into the browser window. If I click in the wrong place, it will cause the Linguist window to disappear, and I will need to click on Linguist again to reopen it. This user experience is not as good as Google Translate, so I hope Linguist can open a separate window for itself, and the input and output windows should be large enough (or dynamically adjust the space they occupy, as Google Translate does).

## What exactly behavior you expect? Describe as many details as possible
There should be a button in Linguist that allows "Text Translation" to open itself as a separate browser window, where the text input and output windows should be large enough, or dynamically change their space, so I can immediately see long texts.

![59](https://github.com/user-attachments/assets/fe9a7469-868f-4283-bf59-d0a4220c4ae8)

**Comment by vitonsky** [comment] 2024-09-26 10:49
It looks as duplicate of #330. Thanks for detailed description, it will be useful while implementing

**Closed** 2024-09-26 14:50 UTC
Labels: duplicate, features
