### ISSUE TITLE
Add speech for the original text (popup button)

### ISSUE THREAD

**Issue by Fred-Vatin** [translate-tools/linguist#249] opened 2023-03-16 06:08 UTC
The feature exists in the main GUI but not in the popup button. I miss it.
![image](https://user-images.githubusercontent.com/22337329/225528906-40f4bbe8-a508-46d2-afba-0a4ee9226924.png)

**Comment by vitonsky** [comment] 2023-03-16 08:10
It's duplicate of #116

This feature is already implemented at master branch. New version will released in the next 2 weeks

![image](https://user-images.githubusercontent.com/86191922/225553552-1acf59be-51a7-4c4f-bd1c-71c1a15d433a.png)

**Comment by vitonsky** [comment] 2023-03-16 08:12
I close this as duplicate, but i like your initiative, feel free to add a new feature requests. Try to find exists issues before create new, but duplicates it's not a critical thing

**Closed** 2023-03-16 08:13 UTC
Labels: duplicate
